name: Generate Metrics

on:
  schedule: [{cron: "0 * * * *"}]  # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Varsha620
          template: classic
          base: header, activity, community, repositories, metadata
          filename: github-metrics.svg

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 5
          plugin_music_playlist: https://open.spotify.com/user/m7ccq34met7wvai6bwm28bf4b?si=2022b58869a7470e

          plugin_pagespeed: yes
          plugin_pagespeed_url: https://vaarsz-dev.netlify.app

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
